[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python debug.py && python -m main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
production.DATABASE_URL = "${DATABASE_URL}"
production.GROQ_API_KEY = "${GROQ_API_KEY}" 